### ISSUE TITLE
What is /tx-info/<txid> status based on?

### ISSUE THREAD

**Issue by MugenTwo** [vsys-host/shkeeper.io#42]
Sorry if this is not the correct place to ask quesions... but I see you are pretty active here.

What is the /tx-info/<txid> "status" propery based on? I read the code and I can't seem to see the big picture.
I tried comparing it with the status of the transaction in the block explorer and it doesn't seem to wait for confirmations.

Do you perhaps assume that the transaction will just be "successful" after sending it the respective crypto's blockchain?

**Comment by dmytro-samoylenko** [comment]
Hello,

`/tx-info/<txid>/<external_id>` endpoint was introduced to show more details about transaction in WHMCS billing system (https://developers.whmcs.com/payment-gateways/transaction-information/) using our Shkeeper module for WHMCS. `status` property only signify if the api request to the endpoint was successful or not. It is not connected in any way with blockchain transaction status. However, any incoming transaction you see in Shkeeper has to be "successful", otherwise it wouldn't be registered within Shkeeper.
