### ISSUE TITLE
several issues

### ISSUE THREAD

**Issue by anycolo** [vsys-host/shkeeper.io#47]
- Periodically, the ETH chain will stop syncing. I restarted shkeeper several times and eventually restarted the server 2 or 3 times in order to get it back up to sync.
- After one of these reboots, it would redirect me back to /login, even if i entered the correct admin and unlock passwords. It now works.
- Amounts displayed in wallets is 0 for every wallet, but i have 2 successful transactions for TRON-USDT in Transactions. Where is the money thought, and how can i spend it? If i click payout on that wallet, the amount displayed is still 0.

And a question:
- Can i create a different set of wallets on the same shkeeper server? I want to sell a different class of products and i want to keep them separate, but i don't want to spin up a new shkeeper instance, because it requires so much SSD.

**Comment by yukonet** [comment]
#Amounts displayed in wallets is 0 for every wallet, but i have 2 successful transactions for TRON-USDT in Transactions. Where is the money thought, and how can i spend it? If i click payout on that wallet, the amount displayed is still 0.

You have received payments to your one-time accounts. To be able to see tokens on your balance and use it, these tokens should be transferred from one-time accounts to the fee-deposit account. This action requires some TRX to be payed as blockchain fee ( usually 13-27 TRX, please check any USDT token transfer at https://tronscan.org).

Please send more than 40TRX to your fee-deposit account (you can find address on USDT payout page in SHKeeper) and tokens will be transferred to the fee-deposit account within an hour.




#Can i create a different set of wallets on the same shkeeper server? I want to sell a different class of products and i want to keep them separate, but i don't want to spin up a new shkeeper instance, because it requires so much SSD.

It is impossible to create a different set of wallets on the same shkeeper server, but you can start a new shkeeper instance using a public ethereum shkeeper full node, which uses much less disk space - https://shkeeper.io/news/released-the-capability-to-use-an-external-node-for-ethereum

**Comment by anycolo** [comment]
Also, some rates are impossible to calculate, such as USDC if the base coin in WHMCS is different from USD.

**Comment by yukonet** [comment]
#13-27 TRX per payment is a bit much. Does this invalidate using USDT/USDC o #ver TRON for small amounts, such as 5-10 US/dollars?

You also have the option in the SHKeeper to automatically add an additional fee to the payment to compensate for transfer costs.


#Also, some rates are impossible to calculate, such as USDC if the base coin in WHMCS is different from USD.

You can add the USD currency (with exchange rate to your main currency) in the WHMCS and in the SHKeeper module and select the USD currency in "Convert To For Processing"

**Comment by anycolo** [comment]
Also, today, something funny happened with an invoice.
![Screenshot from 2024-05-23 15-19-26](https://github.com/vsys-host/shkeeper.io/assets/90413703/c648ff0f-7aa1-44f6-8c46-2aae463713e3)
Does this mean that everytime somebody overpays, i spend tens of TRX to move the extra amount to my wallet? It sounds like a bad idea.

**Comment by yukonet** [comment]
TRX transfer does not require additional TRX, unlike TRC20 tokens. 
TRX will be transferred to a fee-deposit account using free bandwidth.

**Comment by anycolo** [comment]
Yes, but what is happening in those transactions? I don't understand.

**Comment by anycolo** [comment]
And what exactly is INVOICE coin?

**Comment by yukonet** [comment]
The Invoice Coin in the screenshot is the amount of cryptocurrency (which was specified when the invoice was created) that needs to be paid in order for the invoice to become "PAID"

Also, a special feature of Shkeeper is the ability to pay bills in multiple currencies.
If you have  TRX, TRC20 USDC and TRC20 USDT enabled in Shkeeper, the invoice will be marked as Paid if the payment was sent using any of these currencies, given that the paid amount converted to fiat (USD) is enough to settle the invoice.
