### ISSUE TITLE
[SALES / SUPPORT REQUEST] - website contact form doesn't work

### ISSUE THREAD

**Issue by tallship** [vsys-host/shkeeper.io#7]
I'm writing about the WHMCS module for shkeeper.io, and we have a few questions:

1.) I can't find the list of Cryptocurrencies that it supports. This is very important and should be prominently displayed on the front page if you're website.

Can you please send that to me?

Does it support the following?

XLM ADA SOL NANO XRP ZEC and XMR?

Those are the Cryptocurrencies we are interested in and are supported by BTCPayserver, which is also a FOSS GPL v3 license.

2.) To be perfectly clear: We can self-host for free, and integrate a single installation of shkeeper.io simultaneously with our following products and services?

WHMCS, WordPress, WooComerce, basic websites, and our web based restaurant point of sale?

3.) We can send email invoices to people?

4.) I couldn't find a donation page. If it's truly 100% free and open source software, then how do you fund your continued development? Where do we send donations to? Do you have Liberapay, OpenCollective, or Ko-Fi accounts?

5.) To be certain: when (if) we self-host shkeeper, it does not connect to your servers - only full node blockchains and places like Coingecko for the current exchange rates, is that correct?

Thank you, we look forward to hearing back from you very soon - you advertise 24/7/365 support, but one of your customers opened a support ticket in Github that went unanswered for 22 days and that doesn't make you look good or reliable.

6.) Your website contact form doesn't seem to worj either! I tried to send this message several times. No Joy.

We hope it doesn't take you 22 days to respond to our ticket like it did for the other person here when they needed installation help that was because your left a step out of the instructions to create a directory.

Our need us immediate.

Thank you.

**Comment by vsyshost** [comment]
Hello!

Thank you for your interest in SHKeeper.

Answering your questions:

1. Currently, the following coins are available in the SHKeeper:
Bitcoin, Litecoin, Dogecoin.
Also, USDT and USDC / TRX20 are also available.
The coins that you mentioned will be implemented in 2023.
We can add any of these coins in 2 weeks, getting paid for this implementation.

2. Yes.
You can self-host SHKeeper.
There are ready-made modules, and for a premium subscription, we can help to implement even custom modules.

Here is the WHMCS gateway module for SHKeeper, available for free:
https://github.com/vsys-host/whmcs-shkeeper-gateway-module

And here is WordPress + WooCommerce SHKeeper plugin, also available for free:
https://github.com/vsys-host/wp-shkeeper-plugin

3. Invoices must be sent by the CMS/CRM, for which SHKeeper integrates.
The SHKeeper itself processes just payments.

4. The SHKeeper works due to vsys.host and paid/custom subscriptions.
If you want to donate, then you can financially support the Armed Forces of Ukraine.
Do it using the official resources of the Ukrainian Army or "Come Back Alive".

5. You self-host BTC, LTC, and DOGE at your lite node. You don't need a full node for these coins.
For USDT and USDC you can:
- use our TRC full node with our API for free
- or deploy your TRC full node by yourself

6. The website form is working.
We have received several emails from you and have already answered them :)
But just in case, we will check the functionality of the form. Thanks!

--- 

That long answer was an oversight on our part.
We usually respond much faster through the form on the site or by email.

We really provide support 24/7.
If you want to be in touch with us 24/7 - choose the paid or custom SHKeeper version :)

_Please don’t hesitate to ask additional questions about SHKeeper!
I am more than happy to clarify everything or involve our experts if needed.

Looking forward to hearing from you soon! Thanks!_

**Comment by vsyshost** [comment]
Hello @tallship !
 
Please treat the following as a courtesy note.  
 
We sent the requested info but haven’t heard back from you. So, we thought we’d bring up our first email again in case it got lost in your busy inbox.  
  
Yet, we do appreciate you may still have some unanswered questions or doubtful fields. We are more than happy to clarify those in writing, or we can always arrange a call at your convenience. 
 
Please give it a thought and let us know. Thanks.  
 
Regards

**Comment by tallship** [comment]
@vsyshost ,

Yes thank you very much, and I truly appreciate your responsiveness, and your follow up. Apologies for not getting back to you sooner.

We're very impressed with **shkeeper** and looking forward to integrating it into several platforms for ourselves and clients sometime this next year (2023).

The only acceptable solutions for us and the currencies we serve are non-custodial - like yours. Unfortunately, shkeeper does not at this time accept any of the cryptocurrencies we accept, so in the meantime, we deployed **btcpay server**, which supports XMR.

Whereas we now have a noncustodial cryptocurrency payment system that we were able to successfully integrate into WHMCS, it still only supports one cryptocurrency that we accept (Monero).

I've flagged this repo to follow because we're very interested in using your solution, as we feel it has much utility with all of the existing integrations supported (i.e., WHMCS, WordPress, Etc.), and will also recommend to our clients too, but have to wait until support for the previously mentioned currencies are included in shkeeper.

Once again, those are:

* XLM 
* ADA 
* SOL 
* NANO 
* XRP (optional, but integrates with Coil / Interledger)
* ZEC (shielded required)
* XMR (currently using btcpay server).

Like i said, we'll follow the progress of this project and look forward to support for these additional currencies, and you mentioned sopporr for TRC20 which is good because we can support TRX and BTT too.


## The donations you suggested

https://crystalblockchain.com/verified-ukraine-donation-programs-list/ listed this as the XMR address for Dimcharity.com:

**42QgGAw5DJajScgL6zss3VR26K8svDyaz2E9HoywvArR5YECn56SKt2Rq5rXe5bV93jExkfvcuFaNFv23WhoGzrX3MeeGwQ**

Dim international charity says they are using proceeds to purchase *Autel robotics evo pro II 6k* drones. I imagine these will assist your howitzers with target aquisition and they also provide humanitarian aid (food, clothing) for civilians and soldiers.

Those drones are very expensive, and I wish we could do more, but we could only send enough to cover about half the cost of one drone.

We looked at the official government addresses on the crystalblockchain site, and almost sent XLM since that was the only org with a Stellar address, but we decided that we could send more in XMR and especially knowing it would go towards a drone to directly help your troops - we felt it could make the biggest difference.

I hope that helps.

⛵

.

**Comment by vsyshost** [comment]
@tallship 

Firstly, please allow me to use this opportunity to thank you for supporting Ukraine, especially for your donat. It is precious indeed and means a lot to us! 

Secondly, we want to inform you that we are currently working on the Ethereum and ERC-20 tokens. We are in the process right now. 
Talking about your list of coins, we will release part of those coins in 2023. 

If you want to get these coins for yourself faster, we can offer to obtain two coins in return for your subscription to the SHKeeper (the release will be included in the subscription fee). It will take us about two weeks to implement one coin. That means that two weeks are required after purchasing the paid SHKeeper Version for us to realize the first coin of your choice and another two weeks for the second. 

As for the remaining coins, generally speaking, the implementation of one comes at $500 and takes about two weeks. Should you require, those can be implemented additionally.

If you have any additional questions, you are more than welcome to address them with us. Thanks!
