### ISSUE TITLE
how to skip sync in ETH\BNB?

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#74]
like this, but for evm https://github.com/vsys-host/shkeeper.io/issues/18
after install. my progress `Sync In Progress (231214 blocks behind)`

**Comment by yukonet** [comment]
Typically, an Ethereum fullnode does not need to download a snapshot and catches up with the blockchain in a short time.
Since during synchronization the fullnode returns an incorrect value for the last block, the recording of the last block of the fullnode as the last verified block and the start of block verification is blocked by the LAST_BLOCK_LOCKED variable

Only after the fullnode is fully synchronized with the blockchain, you can add


```
ethereum_shkeeper:
  extraEnv:
    LAST_BLOCK_LOCKED: "FALSE"

```

to the values.yaml ​​file and apply it.

If you do this earlier, then the ethereum-shkeeper will be forced to verify all blocks (even those that were before the SHKeeper was installed)

You can change the last verified block to the desired one by running the following commands:

```
kubectl -n shkeeper scale deploy ethereum-shkeeper --replicas=0
kubectl -n shkeeper exec -it <mariadb-pod-name>  -- bash
mysql -uroot -pshkeeper
use ethereum-shkeeper;
update settings set value = '7330688' where name = 'last_block';   # where '7130688' is the desired block number   
exit
kubectl -n shkeeper scale deploy ethereum-shkeeper --replicas=1
```
