### ISSUE TITLE
Taxes reports integration

### ISSUE THREAD

**Issue by musinit** [vsys-host/shkeeper.io#9]
Hello! I love what you do. Open Source is the key for any platform to be Audited, adopted, and trusted.
What do you think about **taxes report**s? We can add integration with some Open Source tax calculation platforms so that people can generate taxes through their crypto transactions.

**Comment by vsyshost** [comment]
@musinit 

Thanks so much for the valuable feedback! It is very much appreciated indeed. 
After putting loads of hard work into our product, it is so pleasing to hear warm words, motivating us to develop it further. By the way, we will provide some updates soon!  

Talking of taxes, it really should take KYC into consideration. Whereas SHKeeper is, first of all, the merchant and ultimate instrument for accepting payments in cryptocurrency. 

Continuing the subject, the vast majority of merchants do not take taxes into account. The reason is CMSs are used for such a role. That is to say; such accounting is carried out through CMS or additional plug-ins.
 
Other than that, we are always open to any reasonable form of cooperation and welcome any activity that eventually leads to our product development. Should you write a module, we will definitely review it! Thanks!
